### ISSUE TITLE
Nav-bar creation

### ISSUE THREAD

**Issue by kadamativenkatasai** [Robotics-Club-BMU/Official-Website#2]
Create a nav-bar of the website with reference to the mentioned features :

**It should be featuring :**
- Club icon             
- Home
- Resources            
- About us
- Documentation    
- Gallery
//The alignment is opinionated. 

**color pallet :**
Red orange - #FD383B
Dark shade of Grey - #1E1E1E
Metallic Silver - #A8A9AD
// you can use online color grabbers like the ColorZilla.

**Look and feel**
- The navbar on a whole should be **sleek**.
- The buttons should have hover effect with a contrast color.
//The hover animation is opinionated and make sure to be consistent.

**** Create a external CSS for the navbar ****

**Comment by anmolj7** [comment]
I would like to work on this, can you assign me this issue ✌️

**Comment by kadamativenkatasai** [comment]
Thats great! sure @anmolj7
